---
title: "R GL Notebook"
output:
  html_notebook: default
---
```{r}
library(rgl)
library(RColorBrewer)
t = seq(1, 6, by = 0.04)
f = function(a, b, c, d, e, f, t) exp(-a*t)*sin(t*b+c)+exp(-d*t)*sin(t*e+f)

v1 = runif(6, 0, 1e-02)
v2 = runif(6, 2, 3)
v3 = runif(6, -pi/2, pi/2)
open3d()
spheres3d(x=f(v1[1], v2[1], v3[1], v1[4], v2[4], v3[4], t),
          y=f(v1[2], v2[2], v3[2], v1[5], v2[5], v3[5], t),
          z=f(v1[3], v2[3], v3[3], v1[6], v2[6], v3[6], t),
          radius=.3, color=sample(brewer.pal(8, "Dark2"),1))
```

```{r}
library(magick)
library(magrittr)
frink <- image_read("https://jeroenooms.github.io/images/frink.png")
image_trim(frink)
image_scale(frink, "200x200")
image_flip(frink)
image_rotate(frink, 45)
image_negate(frink)
frink %>% 
   image_background("green") %>% 
   image_flatten() %>% 
   image_border("red", "10x10")

```

Another more simple plot using the R provided iris data set. Oh, use rglwidget to display the 3D scene within the HTML code
```{r}
library(rglwidget)
```

```{r}
with(iris, plot3d(Sepal.Length, Sepal.Width, Petal.Length, 
                  type = "s", col = as.numeric(Species)))
rglwidget()
```


